# Generated by Django 3.0.6 on 2020-05-28 19:51

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(blank=True, default='', max_length=60)),
                ('lastName', models.CharField(blank=True, default='', max_length=60)),
                ('startingBalance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
            ],
            managers=[
                ('account', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit')], max_length=60)),
                ('ammount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10000)),
                ('description', models.TextField(blank=True, default='', max_length=300)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CheckbookApp.Account')),
            ],
            managers=[
                ('transaction', django.db.models.manager.Manager()),
            ],
        ),
    ]
