# Generated by Django 3.0.6 on 2020-05-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CheckbookApp', '0002_auto_20200528_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='startingBalance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10000),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit')], max_length=60),
        ),
    ]
