# Generated by Django 3.0.6 on 2020-05-29 00:55

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('CheckbookApp', '0004_auto_20200528_1529'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('accounts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('transactions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit')], max_length=60),
        ),
    ]
